name: feature_flag
version: '0.0.1-dev'
description: Provides feature flags for you to use to enable/disable features by a variety of criteria.
repository: 'https://gitlab.com/lachholden/feature-flag'
issue_tracker: 'https://gitlab.com/lachholden/feature-flag/issues'

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
